#-------------------------------------------------------------------------------
# Copyright (C) 2019-2020 Linux4
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------

# Max players (should be an even number > 0)
max-players: 24
# Keep inventory on death
keepinventory: true
# Max amount of each item (0 for unlimited, should be >= 0)
item-cap: 1
# Resupply timer in seconds (should be > 0)
resupply-timer: 11
# enable fireworks on game end, can cause lag for players with low end GPU
enable-fireworks: true
# enable animated explosions, can cause a lot of lag for players with low end GPU
enable-animated-explosions: true
# time before game start, after first player joins
start-countdown: 60
# time before game resets
end-countdown: 30
